### ISSUE TITLE
Access to Code base.

### ISSUE THREAD

**Issue by pawanjenu** [The-Robin-Hood/tamilwordle#1]
Hi can I get access to code base, so that we can make improvements/changes on top of it?
thanks

**Comment by The-Robin-Hood** [comment]
@pawanjenu Will push a separate branch and let you know ;)

**Comment by pawanjenu** [comment]
Great thanks, looking forward to it.

**Comment by The-Robin-Hood** [comment]
@pawanjenu check development branch

**Comment by pawanjenu** [comment]
will go through it, thanks

**Comment by pawanjenu** [comment]
@The-Robin-Hood , 
if possible can you give me a summary of the below?
- for everyday how is the word chosen? I believe from public/word.json
   - but I also see you gave 2 methods in backend (getTamilWords, saveTamilWord)
- how is the word validated? I believe you use an external API: iapi.glosbe.com

if you could just answer the same, that would be great.

**Comment by pawanjenu** [comment]
I am just looking for a top-level flow.

**Comment by The-Robin-Hood** [comment]
Everyday word is chosen from tamilMainWordList -  word.json
The two function: getTamilWords, saveTamilWord is for validation the word 
Validation : 
1. Initially the word will be checked in word.json
2. If it wasn't present in word.json it will fetch for mongoDB.
3. If it wasn't present in DB and then it will fetch the api and if its valid it will store in mongoDB.

@pawanjenu

**Comment by pawanjenu** [comment]
@The-Robin-Hood , while going through the website, I see that you have a limit to 4 letter word only, why is it so?

**Comment by The-Robin-Hood** [comment]
Have you seen the game ? or played it ? Each word consist of just four letters.

**Comment by pawanjenu** [comment]
@The-Robin-Hood , I have played the game, but I have also played games, which have 5 words aswell, was there any reason we are limiting the games to 4 letter.

**Comment by The-Robin-Hood** [comment]
Just to make the game little easier. @pawanjenu
