### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by mvaidhy** [The-Robin-Hood/tamilwordle#3]
Hi

I love solving Tamilwordle. It is the highlight of my morning.

A few suggestions:

1. Randomized keyboards are fixed for a game. By using multiple browsers, we can find the intersection of keyboards to find the solution. A better option would be to create a keyboard that is fixed for each game (across all users) and this keyboard should be created specifically to maximize the number of input word options. Throwing in less used uyirmei letters into keyboard makes parts of the keyboard useless.
2. Supplement your lexicon list with word frequency data, using some standard Tamil text corpus (from contemporary sources, excluding sangam literature etc.). Solutions should come from most used words (say top 10K), and allowed trial words should be picked from these words the and next tier. Obscure words should not be legit. For example, today (Aug 9, 2023), குடம்பு was allowed. It is not even a legitimate word. குடம்பி was also allowed, but that is pretty obscure. 
3. Currently, only word stems are allowed. Many conjugated verbs and declined nouns are not being accepted. I think this is an unnecessary restriction. Perhaps if you can find a lexicon that has both stem and derivative words, it would make it better.

I think the  incorporation of these changes will make the game a lot more playable.

Thanks.

Vaidhy
mvaidhy@hotmail.com

**Comment by The-Robin-Hood** [comment]
Hi @mvaidhy, 
First of all I wanted to express my gratitude for taking the time to provide such a detailed analysis and thoughtful suggestions for improving the Tamilwordle game. Your insights are invaluable in enhancing the overall experience for players like you and I am really surprised that this game reached such distance. 

Your ideas regarding the keyboard design and word selection strategy are indeed intriguing. Regarding the keyboard feature I will definitely work on it and make it as fixed keyboard for each game. Moreover, I completely understand your point about the restrictions on word stems, conjugated verbs, and declined nouns. But the difficulty here is there is not that much source I could gather especially for checking whether the word is actually a proper one or not. So if you found any source please let me know I will definitely look into it.

Given your evident enthusiasm and expertise, I'd be honored if you'd consider collaborating with us to expand the Tamilwordle community. Your contributions could prove instrumental in connecting with fellow enthusiasts and introducing the game to a wider audience. Furthermore, I'd greatly value your assistance in identifying potential developers who could contribute to the betterment of our community.

I want to extend my gratitude once again for your valuable feedback and suggestions. Your dedication to making Tamilwordle an even more enjoyable experience is truly appreciated.

Warm regards,
Ansari

**Comment by mvaidhy** [comment]
Hi ... I am sorry, I just saw your response.

Thank you very much.

I got out of coding some two decades ago, so I don't think I can help you, codewise. But my father (age 87) and I (age 58) solve this puzzle daily and discuss it afterwards. So thanks for keeping it going. 

Today (March 15), there seems to be issue with the puzzle. I see matches that are not consistent.

Thanks!

Vaidhy
![tamilwordle-2024-03-15](https://github.com/The-Robin-Hood/tamilwordle/assets/45543567/825d91a9-dac9-4d48-b62a-4612b96cc267)

**Comment by mvaidhy** [comment]
Another instance
![2024-03-15_2](https://github.com/The-Robin-Hood/tamilwordle/assets/45543567/1549c116-2906-4c76-83c7-0b85306ea271)

**Comment by mvaidhy** [comment]
For what it is worth, I am sending you a link to a recent word list. You can cross check this with your own to see if they can be merge.
https://github.com/aviiciii/tamil-word-frequency/tree/main/output/v3

I saw your YouTube video, too. Good explanation.

**Comment by The-Robin-Hood** [comment]
Thank you for bringing this to my attention. It appears that a five-letter word, **'மறுபிறவி**', was mistakenly added to the database, causing the glitches experienced on March 15. As a result, the game logic was disrupted since a five-letter word was selected. We will promptly remove this word from the list and implement a safety check to prevent similar issues in the future. 😁

@mvaidhy
